#title: Doing Stuff
#page_name: Welcome 
username: J. Steve Martinez
description: Learning Jekyll
blog_name: Bloggy the Blog
email: stevemart@comcast.net
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "https://j-steve-martinez.github.com" # the base hostname & protocol for your site
twitter_username: j_steve_m
github_username:  j-steve-martinez

# Build settings
markdown: redcarpet
