# Site settings
title: J. Steve Martinez
short: Doing Stuff
email: j.steve.martinez@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Powered by Jekyll
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://j-steve-martinez.github.com" # the base hostname & protocol for your site
twitter_username: j_steve_m
github_username:  j-steve-martinez

# Build settings
markdown: kramdown

collections:
 projects:
  output: true