# Site settings
title: Welcome
short: Doing Stuff
email: j.steve.martinez@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This is a site for leaning how to use the different web tools in use today.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://j-steve-martinez.github.com" # the base hostname & protocol for your site
twitter_username: j_steve_m
github_username:  j-steve-martinez

# Build settings
markdown: kramdown
